### ISSUE TITLE
--task-id-prefixと--frame_per_taskがない状態でupload_sceneすると、原因が非常に分かりにくいエラーでタスクの生成に失敗する

### ISSUE THREAD

**Issue by seraphr** [kurusugawa-computer/annofab-3dpc-editor-cli#76]
原因は↓でtask_idが空になってしまうため。

https://github.com/kurusugawa-computer/annofab-3dpc-editor-cli/blob/b6bd94c33d9a84c78c1f6658e8d176ab9b9cebd6/anno3d/kitti/scene_uploader.py#L126-L143

`--task-id-prefix`は必須にして、空文字列だったらその旨エラーにするようにすべきか
少なくとも、↑の部分でtask_idが空になってしまったら、その旨のエラーにすべき

**Comment by yuji38kwmt** [comment]
#91 #99 によりクローズ
